export const IMAGE_PATHS = {
  HEADER: {
    NAV_HOVER_ABOUT: '/img/header/nav-hover/about.png',
    NAV_HOVER_SKILLS: '/img/header/nav-hover/skills.png',
    NAV_HOVER_PROJECTS: '/img/header/nav-hover/projects.png',
    NAV_HOVER_CONTACT: '/img/header/nav-hover/contact.png',
  },
  HERO: {
    BACKGROUND: '/img/hero/hero-bg.png',
    POLAROID_FRAME: '/img/hero/polaroid-frame.png',
    PHOTO: '/img/hero/pb.jpg',
    WAVING_HAND: '/img/hero/waving_hand.svg',
  },
  ABOUT_ME: {
    STICKER_YELLOW: '/img/about-me/sticker-yellow.png',
    STICKER_BLUE: '/img/about-me/sticker-blue.png',
    STICKER_ORANGE: '/img/about-me/sticker-orange.png',
    UNDERLINE: '/img/about-me/underline.png',
    LOCATION: '/img/about-me/location.svg',
    REMOTE: '/img/about-me/remote.svg',
    RELOCATE: '/img/about-me/relocate.svg',
  },
  SKILLS: {
    BACKGROUND: '/img/skills/skills-bg.png',
    DESCRIPTION: '/img/skills/skills-description.png',
    DESCRIPTION_MOBILE: '/img/skills/skills-description-mobile.png',
    BADGE_DEFAULT: '/img/skills/badge-default.png',
    BADGE_TRANSITION: '/img/skills/badge-transition.png',
    BADGE_FINAL: '/img/skills/badge-final.png',
    UNDERLINE: '/img/skills/underline.png',
    ARROW: '/img/skills/arrow.png',
    CSS: '/img/skills/css.svg',
    HTML: '/img/skills/html.svg',
    JAVASCRIPT: '/img/skills/javascript.svg',
    TYPESCRIPT: '/img/skills/typescript.svg',
    ANGULAR: '/img/skills/angular.svg',
    FIREBASE: '/img/skills/firebase.svg',
    GIT: '/img/skills/git.svg',
    REST_API: '/img/skills/rest-api.svg',
    SCRUM: '/img/skills/scrum.svg',
    MATERIAL_DESIGN: '/img/skills/material-design.svg',
  },
  PROJECTS: {
    JOIN: '/img/projects/join.svg',
    POLLO_LOCO: '/img/projects/pollo_loco.svg',
    DABUBBLE: '/img/projects/bubble.svg',
    UNDERLINE: '/img/projects/underline.png',
  },
  COLLEAGUES: {
    UNDERLINE: '/img/testimonials/underline.png',
  },
  CONTACT: {
    UNDERLINE: '/img/contact/underline.png',
  },
  FOOTER: {
    BACKGROUND: '/img/footer/footer-bg.png',
    GITHUB: '/img/footer/github.svg',
    LINKEDIN: '/img/footer/linkedin.svg',
    EMAIL: '/img/footer/email.svg',
  },
  SHARED: {
    CHECK: '/img/shared/check.png',
    TOGGLE: '/img/shared/toggle.png',
    FEATURED: '/img/shared/featured.svg',
    GITHUB: '/img/shared/github.svg',
    LINKEDIN: '/img/shared/linkedin.svg',
    EMAIL: '/img/shared/email.svg',
  },
  PROJECT_PAGES: {
    NOTEBOOK_PAPER: '/img/project-pages/notebook-paper.png',
    JOIN: '/img/project-pages/join.svg',
  },
  LOGO: '/logo/logo.svg',
} as const;
